### ISSUE TITLE
Issue with useAppleColor check in CSystemColors.m

### ISSUE THREAD

**Issue by sophia-guo** [ibmruntimes/openj9-openjdk-jdk15#47]
The issue was reported and solved in https://bugs.openjdk.java.net/browse/JDK-8253791. The fix is https://github.com/ibmruntimes/openj9-openjdk-jdk/commit/6e926d9a00967fcf65fd467185fdb8a3e9b34ac7. Thought it was not back ported to 15.

**Comment by sophia-guo** [comment]
@pshipton will the fix be back ported to 15? I'd like to confirm this so we will probably disable jdk 15 on Mac on build-openj9 github action. Thanks.

**Comment by pshipton** [comment]
@sophia-guo The issue contains the tags `jdk15u-fix-request` and `jdk15u-fix-yes` so I assume it's going to be backported. There won't be any OpenJDK changes to the jdk15 repo until the 15.0.2 release date, Jan 19th 2021.

**Comment by AdamBrousseau** [comment]
@pshipton fyi I'm closing so I can archive this repo.
